import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
    await page.goto('https://app.thetestingacademy.com/playwright/ttacart/');
    await page.locator('[data-test="username"]').click();
    await page.locator('[data-test="username"]').fill('standard_user');
    await page.locator('[data-test="password"]').click();
    await page.locator('[data-test="password"]').fill('tta_secret');
    await page.locator('[data-test="login-button"]').click();
    await page.locator('[data-test="add-to-cart-test-allthethings-tshirt-red"]').click();
    await page.locator('[data-test="shopping-cart-link"]').click();
    await page.locator('[data-test="remove-test-allthethings-tshirt-red"]').click();
    await page.locator('[data-test="continue-shopping"]').click();
    await page.locator('[data-test="add-to-cart-test-allthethings-tshirt-red"]').click();
    await page.locator('[data-test="shopping-cart-link"]').click();
    await page.locator('[data-test="checkout"]').click();
    await page.locator('[data-test="firstName"]').click();
    await page.locator('[data-test="firstName"]').press('CapsLock');
    await page.locator('[data-test="firstName"]').fill('T');
    await page.locator('[data-test="firstName"]').press('CapsLock');
    await page.locator('[data-test="firstName"]').fill('Testuser');
    await page.locator('[data-test="lastName"]').click();
    await page.locator('[data-test="lastName"]').press('CapsLock');
    await page.locator('[data-test="lastName"]').fill('T');
    await page.locator('[data-test="lastName"]').press('CapsLock');
    await page.locator('[data-test="postalCode"]').click();
    await page.locator('[data-test="postalCode"]').fill('600033');
    await page.locator('[data-test="cancel"]').click();
    await page.locator('[data-test="checkout"]').click();
    await page.locator('[data-test="continue"]').click();
    await expect(page.locator('[data-test="error"]')).toBeVisible();
    await expect(page.locator('[data-test="error"]')).toContainText('Error: First Name is required');
    await page.locator('[data-test="firstName"]').click();
    await page.locator('[data-test="firstName"]').fill('Testuser');
    await page.locator('[data-test="lastName"]').click();
    await page.locator('[data-test="lastName"]').fill('testing');
    await page.locator('[data-test="postalCode"]').click();
    await page.locator('[data-test="postalCode"]').fill('600033');
    await page.locator('[data-test="continue"]').click();
    await page.locator('[data-test="finish"]').click();
    await expect(page.locator('[data-test="complete-header"]')).toBeVisible();
    await expect(page.locator('[data-test="complete-text"]')).toContainText('Your order has been dispatched, and will arrive just as fast as the TTA Express pony can get there!');
    await page.locator('[data-test="back-to-products"]').click();
    await expect(page.locator('[data-test="primary-header"]').getByText('TTACart')).toBeVisible();
    await expect(page.locator('[data-test="primary-header"] span')).toContainText('TTACart');
});